apiVersion: v1
kind: Pod
metadata:
    name: my-nginx 
spec:
    containers: 
       - name: nginx-container
         image: nginx
         ports:
            - containerPort: 80
        
          
    


